-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- account.support_tier is synced from ServiceNow's u_support_timezone field,
-- NOT u_support_tier. This is not a typo: production ServiceNow has a known
-- data-integrity bug where u_support_tier and u_support_timezone were
-- relabelled at some point without migrating the underlying data, so the
-- real tier value lives in u_support_timezone despite its name. Mirrors the
-- column added to the shared account table (created here in
-- 000008_accounts_table.up.sql) by a companion change in
-- digiops-cs/operations/csm-sync-service, which is the authoritative source
-- for what's actually applied to the real shared database.
ALTER TABLE account ADD COLUMN IF NOT EXISTS support_tier VARCHAR(255);
